# FROM node:16.14-alpine as production

# ARG NODE_ENV=production
# ENV NODE_ENV=${NODE_ENV}

# WORKDIR /usr/src/app

# COPY package*.json ./

# COPY yarn.lock ./

# RUN yarn --only=production

# COPY . .

# RUN yarn build

# CMD ["node", "dist/main"]


# Use the official Node.js image as the base image
FROM node:20 as production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the NestJS application
RUN npm run build

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["node", "dist/main"]